import { describe, expect, it } from 'vitest';
import { generateSigningSecret, signPayload, verifySignature } from './sign';

// from standardwebhooks 1.1.1, so a construction Svix and Resend would reject fails here
const REFERENCE = {
  secret: 'whsec_+FAoXzy3Ow5aG8DJG8W+/rFJ4b6rFab/dM9dDhx+lbc=',
  messageId: 'msg_2Zv8K3nQxW1pR7tLbYcHdFgJ',
  timestampSeconds: 1758585600,
  payload:
    '{"type":"email.delivered","created_at":"2026-09-23T00:00:00.000Z","data":{"email_id":"8f14e45f-ceea-467a-9f1a-7b0d1e3a4c52"}}',
  signature: 'v1,67Jlxo25jD/KY2yrJ3UBZcwp0AeoJAStABNhEMx14SY=',
};

const TOLERANCE_SECONDS = 300;

function currentTimestamp(): number {
  return Math.floor(Date.now() / 1000);
}

function signedAt(timestampSeconds: number) {
  const secret = generateSigningSecret();
  const payload = '{"type":"email.bounced","data":{"email_id":"7c3f"}}';
  const { headers } = signPayload({
    secret,
    messageId: 'msg_test',
    timestampSeconds,
    payload,
  });

  return { secret, payload, header: headers['webhook-signature'] ?? '' };
}

describe('generateSigningSecret', () => {
  it('formats a secret as the whsec_ prefix and 32 base64 encoded bytes', () => {
    const secret = generateSigningSecret();

    expect(secret).toMatch(/^whsec_[A-Za-z0-9+/]{43}=$/);
    expect(Buffer.from(secret.slice('whsec_'.length), 'base64')).toHaveLength(32);
  });

  it('never repeats a secret', () => {
    const secrets = new Set(Array.from({ length: 1000 }, generateSigningSecret));

    expect(secrets.size).toBe(1000);
  });
});

describe('signPayload', () => {
  it('reproduces a signature generated by the reference implementation', () => {
    const { headers } = signPayload(REFERENCE);

    expect(headers['webhook-signature']).toBe(REFERENCE.signature);
  });

  it('sends the message id and timestamp the reference implementation signed', () => {
    const { headers } = signPayload(REFERENCE);

    expect(headers['webhook-id']).toBe(REFERENCE.messageId);
    expect(headers['webhook-timestamp']).toBe(String(REFERENCE.timestampSeconds));
  });

  it('returns the exact bytes it signed, so the caller never serializes a second time', () => {
    const { body } = signPayload(REFERENCE);

    expect(body).toBe(REFERENCE.payload);
  });

  it('signs a different payload differently under the same secret and timestamp', () => {
    const { headers } = signPayload({ ...REFERENCE, payload: '{"type":"email.bounced"}' });

    expect(headers['webhook-signature']).not.toBe(REFERENCE.signature);
  });
});

describe('verifySignature', () => {
  it('accepts a signature it produced for the same payload', () => {
    const timestampSeconds = currentTimestamp();
    const { secret, payload, header } = signedAt(timestampSeconds);

    expect(
      verifySignature({ secret, messageId: 'msg_test', timestampSeconds, payload, header }),
    ).toBe(true);
  });

  it('rejects a payload edited after it was signed', () => {
    const timestampSeconds = currentTimestamp();
    const { secret, header } = signedAt(timestampSeconds);

    expect(
      verifySignature({
        secret,
        messageId: 'msg_test',
        timestampSeconds,
        payload: '{"type":"email.bounced","data":{"email_id":"0000"}}',
        header,
      }),
    ).toBe(false);
  });

  it('rejects a timestamp older than the tolerance window', () => {
    const timestampSeconds = currentTimestamp() - TOLERANCE_SECONDS - 1;
    const { secret, payload, header } = signedAt(timestampSeconds);

    expect(
      verifySignature({ secret, messageId: 'msg_test', timestampSeconds, payload, header }),
    ).toBe(false);
  });

  it('rejects a timestamp further ahead than the tolerance window', () => {
    const timestampSeconds = currentTimestamp() + TOLERANCE_SECONDS + 1;
    const { secret, payload, header } = signedAt(timestampSeconds);

    expect(
      verifySignature({ secret, messageId: 'msg_test', timestampSeconds, payload, header }),
    ).toBe(false);
  });

  it('rejects a signature made with a different secret', () => {
    const timestampSeconds = currentTimestamp();
    const { payload, header } = signedAt(timestampSeconds);

    expect(
      verifySignature({
        secret: generateSigningSecret(),
        messageId: 'msg_test',
        timestampSeconds,
        payload,
        header,
      }),
    ).toBe(false);
  });

  it('rejects a signature made for a different message id', () => {
    const timestampSeconds = currentTimestamp();
    const { secret, payload, header } = signedAt(timestampSeconds);

    expect(
      verifySignature({ secret, messageId: 'msg_other', timestampSeconds, payload, header }),
    ).toBe(false);
  });

  it.each([
    ['empty', ''],
    ['no version segment', '67Jlxo25jD/KY2yrJ3UBZcwp0AeoJAStABNhEMx14SY='],
    ['unknown version', 'v2,67Jlxo25jD/KY2yrJ3UBZcwp0AeoJAStABNhEMx14SY='],
    ['version only', 'v1,'],
    ['not base64', 'v1,not a signature'],
    ['separated by commas rather than spaces', 'v1,aaaa,v1,bbbb'],
  ])('rejects a malformed header: %s', (_label, header) => {
    const timestampSeconds = currentTimestamp();
    const { secret, payload } = signedAt(timestampSeconds);

    expect(
      verifySignature({ secret, messageId: 'msg_test', timestampSeconds, payload, header }),
    ).toBe(false);
  });

  it('accepts the matching signature when the header carries two space separated values', () => {
    const timestampSeconds = currentTimestamp();
    const { secret, payload, header } = signedAt(timestampSeconds);
    const stale = signPayload({
      secret: generateSigningSecret(),
      messageId: 'msg_test',
      timestampSeconds,
      payload,
    }).headers['webhook-signature'];

    expect(
      verifySignature({
        secret,
        messageId: 'msg_test',
        timestampSeconds,
        payload,
        header: `${stale} ${header}`,
      }),
    ).toBe(true);
  });
});
